/**
 * Research batches. Tier A = travel available + est. ≥15% success for strong applicants.
 */
import type { TravelPriorityCircuit } from './travel-priority'

export const TIER_A_RESEARCH_BATCH: TravelPriorityCircuit[] = [
  {
    id: 'yhack',
    label: 'YHack',
    tier: 'A',
    region: 'na',
    titlePattern: /\by\s*hack\b|\byhack\b/i,
    hostPatterns: [/yhack\.org$/i],
    faqPaths: ['/faq', '/travel'],
    siteUrl: 'https://yhack.org/',
    evidence: 'Accepted can apply for reimbursement; East Coast priority (≥15%)',
  },
  {
    id: 'conuhacks',
    label: 'ConUHacks',
    tier: 'A',
    region: 'na',
    titlePattern: /\bconu\s*hacks\b/i,
    hostPatterns: [/conuhacks\.io$/i],
    faqPaths: ['/faq', '/travel'],
    siteUrl: 'https://www.conuhacks.io/',
    evidence: 'Up to $150 CAD / $100 USD per person — published pool',
  },
  {
    id: 'technica',
    label: 'Technica',
    tier: 'A',
    region: 'na',
    titlePattern: /\btechnica\b/i,
    hostPatterns: [/gotechnica\.org$/i],
    faqPaths: ['/faq', '/travel'],
    siteUrl: 'https://gotechnica.org/',
    evidence: 'Documented reimbursement program',
  },
  {
    id: 'bigredhacks',
    label: 'BigRed//Hacks',
    tier: 'A',
    region: 'na',
    titlePattern: /\bbig\s*red\s*hacks\b|\bbigred\/\/hacks\b/i,
    hostPatterns: [/bigredhacks\.com$/i],
    faqPaths: ['/faq', '/travel'],
    siteUrl: 'https://www.bigredhacks.com/',
    evidence: 'Historical case-by-case ~$150 + buses',
  },
  {
    id: 'hacksc',
    label: 'HackSC',
    tier: 'A',
    region: 'na',
    titlePattern: /\bhack\s*sc\b/i,
    hostPatterns: [/hacksc\.com$/i],
    faqPaths: ['/faq', '/travel'],
    siteUrl: 'https://hacksc.com/',
    evidence: 'Community guides list travel support',
  },
  {
    id: 'adventurex',
    label: 'AdventureX',
    tier: 'A',
    region: 'asia',
    titlePattern: /\badventure\s*x\b/i,
    hostPatterns: [/adventure-x\.org$/i],
    faqPaths: ['/zh', '/en', '/faq'],
    siteUrl: 'https://adventure-x.org/',
    evidence: 'Official 旅费补助 for distant + student 差旅; international',
  },
  {
    id: 'duke-nus-ghi',
    label: 'APAC Global Health Innovation Hackathon',
    tier: 'A',
    region: 'asia',
    titlePattern: /global health innovation hackathon|duke-?nus.*hack/i,
    hostPatterns: [/duke-nus\.edu\.sg$/i],
    faqPaths: [],
    siteUrl: 'https://www.duke-nus.edu.sg/sdghi/news-events/events/innovation-hackathon',
    evidence: 'LMIC teams: travel fully covered when selected',
  },
  // Promoted under ≥15% rule
  {
    id: 'junction',
    label: 'Junction',
    tier: 'A',
    region: 'eu',
    titlePattern: /\bjunction\b/i,
    hostPatterns: [/hackjunction\.com$/i, /junction\.fi$/i],
    faqPaths: ['/faq', '/travel', '/info'],
    siteUrl: 'https://www.hackjunction.com/',
    evidence:
      'Tier A (≥15%): limited grants (e.g. ~€300) — not everyone, but real pool for accepted international',
  },
  {
    id: 'easya',
    label: 'EasyA',
    tier: 'A',
    region: 'global',
    titlePattern: /\beasy\s*a\b/i,
    hostPatterns: [/easya\.io$/i],
    faqPaths: ['/faq', '/travel'],
    siteUrl: 'https://www.easya.io/',
    evidence: 'Tier A (≥15%): repeatedly cited for travel support on selected events',
  },
  {
    id: 'encode',
    label: 'Encode',
    tier: 'A',
    region: 'global',
    titlePattern: /\bencode\b/i,
    hostPatterns: [/encode\.club$/i],
    faqPaths: ['/faq', '/travel'],
    siteUrl: 'https://www.encode.club/',
    evidence: 'Tier A (≥15%): travel/stipend for selected builders on many programs',
  },
  {
    id: 'pearlhacks',
    label: 'Pearl Hacks',
    tier: 'A',
    region: 'na',
    titlePattern: /\bpearl\s*hacks\b/i,
    hostPatterns: [/pearlhacks\.com$/i],
    faqPaths: ['/faq', '/travel'],
    siteUrl: 'https://pearlhacks.com/',
    evidence: 'Tier A (≥15%): limited support some years — apply when FAQ open',
  },
]

export const TIER_B_RESEARCH_BATCH: TravelPriorityCircuit[] = [
  {
    id: 'isro-bah',
    label: 'ISRO Antariksh Hackathon',
    tier: 'B',
    region: 'asia',
    titlePattern: /\bantariksh\b|\bisro\b.*hack|\bbharatiya\s+antariksh\b/i,
    hostPatterns: [/hack2skill\.com$/i],
    faqPaths: [],
    siteUrl: 'https://hack2skill.com/event/bah2026/',
    evidence: 'Finalists only — national funnel <<15% of applicants',
  },
  {
    id: 'mchacks',
    label: 'McHacks',
    tier: 'B',
    region: 'na',
    titlePattern: /\bmc\s*hacks\b/i,
    hostPatterns: [/mchacks\.ca$/i],
    faqPaths: ['/faq'],
    siteUrl: 'https://mchacks.ca/',
    evidence: '2026 FAQ: not offering — year-off',
  },
  {
    id: 'sfhacks',
    label: 'SF Hacks',
    tier: 'B',
    region: 'na',
    titlePattern: /\bsf\s*hacks\b/i,
    hostPatterns: [/sfhacks\.io$/i],
    faqPaths: ['/faqs', '/faq'],
    siteUrl: 'https://www.sfhacks.io/',
    evidence: 'No published travel policy',
  },
  {
    id: 'cathay-hackathon',
    label: 'Cathay Hackathon',
    tier: 'B',
    region: 'asia',
    titlePattern: /\bcathay\s*hack/i,
    hostPatterns: [/cathaypacific\.com$/i],
    faqPaths: [],
    siteUrl: 'https://news.cathaypacific.com/',
    evidence: 'Winner-only flights — <<15%',
  },
  {
    id: 'ethglobal',
    label: 'ETHGlobal',
    tier: 'B',
    region: 'global',
    titlePattern: /eth\s?global/i,
    hostPatterns: [/ethglobal\.com$/i],
    faqPaths: ['/faq', '/travel', '/perks', '/scholarships'],
    siteUrl: 'https://ethglobal.com/',
    evidence:
      'Scholarships exist but X shows most accepted still self-fund — est. below 15% for open travel',
  },
]
