/**
 * Research batches. Tier A = travel available + est. ≥15% for eligible applicants.
 */
import type { TravelPriorityCircuit } from './travel-priority'

export const TIER_A_RESEARCH_BATCH: TravelPriorityCircuit[] = [
  {
    id: 'yhack',
    label: 'YHack',
    tier: 'A',
    region: 'na',
    titlePattern: /\by\s*hack\b|\byhack\b/i,
    hostPatterns: [/yhack\.org$/i],
    faqPaths: ['/faq', '/travel'],
    siteUrl: 'https://yhack.org/',
    evidence: 'Accepted can apply for reimbursement; East Coast priority',
  },
  {
    id: 'conuhacks',
    label: 'ConUHacks',
    tier: 'A',
    region: 'na',
    titlePattern: /\bconu\s*hacks\b/i,
    hostPatterns: [/conuhacks\.io$/i],
    faqPaths: ['/faq', '/travel'],
    siteUrl: 'https://www.conuhacks.io/',
    evidence: 'Up to $150 CAD / $100 USD per person',
  },
  {
    id: 'technica',
    label: 'Technica',
    tier: 'A',
    region: 'na',
    titlePattern: /\btechnica\b/i,
    hostPatterns: [/gotechnica\.org$/i],
    faqPaths: ['/faq', '/travel'],
    siteUrl: 'https://gotechnica.org/',
    evidence: 'Documented reimbursement program',
  },
  {
    id: 'bigredhacks',
    label: 'BigRed//Hacks',
    tier: 'A',
    region: 'na',
    titlePattern: /\bbig\s*red\s*hacks\b|\bbigred\/\/hacks\b/i,
    hostPatterns: [/bigredhacks\.com$/i],
    faqPaths: ['/faq', '/travel'],
    siteUrl: 'https://www.bigredhacks.com/',
    evidence: 'Historical case-by-case ~$150 + buses',
  },
  {
    id: 'hacksc',
    label: 'HackSC',
    tier: 'A',
    region: 'na',
    titlePattern: /\bhack\s*sc\b/i,
    hostPatterns: [/hacksc\.com$/i],
    faqPaths: ['/faq', '/travel'],
    siteUrl: 'https://hacksc.com/',
    evidence: 'Community guides list travel support',
  },
  {
    id: 'adventurex',
    label: 'AdventureX',
    tier: 'A',
    region: 'asia',
    titlePattern: /\badventure\s*x\b/i,
    hostPatterns: [/adventure-x\.org$/i],
    faqPaths: ['/zh', '/en', '/faq'],
    siteUrl: 'https://adventure-x.org/',
    evidence: 'Official 旅费补助 for distant + student 差旅',
  },
  {
    id: 'duke-nus-ghi',
    label: 'APAC Global Health Innovation Hackathon',
    tier: 'A',
    region: 'asia',
    titlePattern: /global health innovation hackathon|duke-?nus.*hack/i,
    hostPatterns: [/duke-nus\.edu\.sg$/i],
    faqPaths: [],
    siteUrl: 'https://www.duke-nus.edu.sg/sdghi/news-events/events/innovation-hackathon',
    evidence: 'LMIC teams: travel fully covered when selected',
  },
  {
    id: 'junction',
    label: 'Junction',
    tier: 'A',
    region: 'eu',
    titlePattern: /\bjunction\b/i,
    hostPatterns: [/hackjunction\.com$/i, /junction\.fi$/i],
    faqPaths: ['/faq', '/travel', '/info'],
    siteUrl: 'https://www.hackjunction.com/',
    evidence: 'Limited grants (~€300) for accepted international — ≥15% pool',
  },
  {
    id: 'easya',
    label: 'EasyA',
    tier: 'A',
    region: 'global',
    titlePattern: /\beasy\s*a\b/i,
    hostPatterns: [/easya\.io$/i],
    faqPaths: ['/faq', '/travel'],
    siteUrl: 'https://www.easya.io/',
    evidence: 'Travel support on selected events',
  },
  {
    id: 'encode',
    label: 'Encode',
    tier: 'A',
    region: 'global',
    titlePattern: /\bencode\b/i,
    hostPatterns: [/encode\.club$/i],
    faqPaths: ['/faq', '/travel'],
    siteUrl: 'https://www.encode.club/',
    evidence: 'Travel/stipend for selected builders',
  },
  {
    id: 'pearlhacks',
    label: 'Pearl Hacks',
    tier: 'A',
    region: 'na',
    titlePattern: /\bpearl\s*hacks\b/i,
    hostPatterns: [/pearlhacks\.com$/i],
    faqPaths: ['/faq', '/travel'],
    siteUrl: 'https://pearlhacks.com/',
    evidence: 'Limited support some years when FAQ open',
  },
  // 2026-07-19 site-verified
  {
    id: 'hackrice',
    label: 'HackRice',
    tier: 'A',
    region: 'na',
    titlePattern: /\bhack\s*rice\b/i,
    hostPatterns: [/hackrice\.com$/i],
    faqPaths: ['/faq', '/'],
    siteUrl: 'https://hackrice.com/',
    evidence:
      'Official FAQ 2026: travel stipends offered — "majority of our budget goes towards" this; amounts later summer; Sep 11–13 2026 Houston',
  },
  {
    id: 'vthacks',
    label: 'VTHacks',
    tier: 'A',
    region: 'na',
    titlePattern: /\bvt\s*hacks\b|\bvthacks\b/i,
    hostPatterns: [/vthacks\.com$/i],
    faqPaths: ['/faq', '/'],
    siteUrl: 'https://vthacks.com/',
    evidence:
      'Official FAQ: "Not from Blacksburg? We selectively offer travel reimbursements!" — ≥15% for strong non-local applicants',
  },
  {
    id: 'hackkosice',
    label: 'Hack Kosice',
    tier: 'A',
    region: 'eu',
    titlePattern: /\bhack\s*ko[sš]ice\b/i,
    hostPatterns: [/hackkosice\.com$/i],
    faqPaths: ['/faq', '/travel-guide', '/travel'],
    siteUrl: 'https://hackkosice.com/',
    evidence:
      'Official: travel reimbursed €20 from PL/CZ/HU/AT/UA and €50 from further abroad, plus accommodation — apply in portal, submit a project, show receipts',
  },
  {
    id: 'ethindia',
    label: 'ETHIndia',
    tier: 'A',
    region: 'asia',
    titlePattern: /\beth\s*india\b/i,
    hostPatterns: [/ethindia\.co$/i, /ethindia.*\.devfolio\.co$/i],
    faqPaths: ['/faq'],
    siteUrl: 'https://ethindia.co/',
    evidence:
      'Devfolio flagship (Bangalore, Sep); accepted hackers hosted with accommodation + food and travel support offered in several editions — reputation-based, verify current-edition FAQ',
  },
]

export const TIER_B_RESEARCH_BATCH: TravelPriorityCircuit[] = [
  {
    id: 'isro-bah',
    label: 'ISRO Antariksh Hackathon',
    tier: 'B',
    region: 'asia',
    titlePattern: /\bantariksh\b|\bisro\b.*hack|\bbharatiya\s+antariksh\b/i,
    hostPatterns: [/hack2skill\.com$/i],
    faqPaths: [],
    siteUrl: 'https://hack2skill.com/event/bah2026/',
    evidence: 'Finalists only — national funnel <<15%',
  },
  {
    id: 'mchacks',
    label: 'McHacks',
    tier: 'B',
    region: 'na',
    titlePattern: /\bmc\s*hacks\b/i,
    hostPatterns: [/mchacks\.ca$/i],
    faqPaths: ['/faq'],
    siteUrl: 'https://mchacks.ca/',
    evidence: '2026 FAQ: not offering',
  },
  {
    id: 'sfhacks',
    label: 'SF Hacks',
    tier: 'B',
    region: 'na',
    titlePattern: /\bsf\s*hacks\b/i,
    hostPatterns: [/sfhacks\.io$/i],
    faqPaths: ['/faqs', '/faq'],
    siteUrl: 'https://www.sfhacks.io/',
    evidence: 'No published travel policy',
  },
  {
    id: 'cathay-hackathon',
    label: 'Cathay Hackathon',
    tier: 'B',
    region: 'asia',
    titlePattern: /\bcathay\s*hack/i,
    hostPatterns: [/cathaypacific\.com$/i],
    faqPaths: [],
    siteUrl: 'https://news.cathaypacific.com/',
    evidence: 'Winner-only flights',
  },
  {
    id: 'ethglobal',
    label: 'ETHGlobal',
    tier: 'B',
    region: 'global',
    titlePattern: /eth\s?global/i,
    hostPatterns: [/ethglobal\.com$/i],
    faqPaths: ['/faq', '/travel'],
    siteUrl: 'https://ethglobal.com/',
    evidence: 'Scholarships exist but most accepted self-fund',
  },
  {
    id: 'hophacks',
    label: 'HopHacks',
    tier: 'B',
    region: 'na',
    titlePattern: /\bhop\s*hacks\b/i,
    hostPatterns: [/hophacks\.com$/i],
    faqPaths: ['/faq'],
    siteUrl: 'https://hophacks.com/',
    evidence: '2026: no individual travel reimbursements; bus only if enough interest',
  },
  {
    id: 'shellhacks',
    label: 'ShellHacks',
    tier: 'B',
    region: 'na',
    titlePattern: /\bshell\s*hacks\b/i,
    hostPatterns: [/shellhacks\.net$/i],
    faqPaths: ['/faq'],
    siteUrl: 'https://shellhacks.net/',
    evidence: 'No travel policy on site (Sep 2026 edition)',
  },
  {
    id: 'hackzurich',
    label: 'HackZurich',
    tier: 'B',
    region: 'eu',
    titlePattern: /\bhack\s*z[uü]rich\b/i,
    hostPatterns: [/hackzurich\.com$/i],
    faqPaths: ['/faq'],
    siteUrl: 'https://hackzurich.com/',
    evidence: 'Application-only; travel support for accepted internationals is selective — verify FAQ',
  },
  {
    id: 'colosseum',
    label: 'Colosseum',
    tier: 'B',
    region: 'global',
    titlePattern: /\bcolosseum\b/i,
    hostPatterns: [/colosseum\.(org|com)$/i],
    faqPaths: [],
    siteUrl: 'https://www.colosseum.org/',
    evidence: 'Online Solana hackathon; only finalists travel to the in-person demo day',
  },
  {
    id: 'hackharvard',
    label: 'HackHarvard',
    tier: 'B',
    region: 'na',
    titlePattern: /\bhack\s*harvard\b/i,
    hostPatterns: [/hackharvard\.io$/i],
    faqPaths: ['/faq'],
    siteUrl: 'https://hackharvard.io/',
    evidence: 'MLH event; occasional selective travel stipends — verify FAQ',
  },
  {
    id: 'ethdenver',
    label: 'ETHDenver',
    tier: 'B',
    region: 'na',
    titlePattern: /\beth\s*denver\b/i,
    hostPatterns: [/ethdenver\.com$/i],
    faqPaths: ['/faq'],
    siteUrl: 'https://www.ethdenver.com/',
    evidence: 'Scholar program covers some travel; most attendees self-fund',
  },
  {
    id: 'deltahacks',
    label: 'DeltaHacks',
    tier: 'B',
    region: 'na',
    titlePattern: /\bdelta\s*hacks\b/i,
    hostPatterns: [/deltahacks\.com$/i],
    faqPaths: ['/faq'],
    siteUrl: 'https://deltahacks.com/',
    evidence: 'McMaster MLH event; travel policy unclear/limited — verify FAQ',
  },
  {
    id: 'ichack',
    label: 'IC Hack (Imperial College London)',
    tier: 'B',
    region: 'eu',
    titlePattern: /\bic[- ]?hack\b/i,
    hostPatterns: [/ichack\.org$/i],
    faqPaths: ['/faq', '/faqs'],
    siteUrl: 'https://ichack.org/',
    evidence: "UK's largest student-run hackathon (Imperial College London); travel support varies by edition — verify FAQ",
  },
  {
    id: 'hacktheburgh',
    label: 'HackTheBurgh',
    tier: 'B',
    region: 'eu',
    titlePattern: /\bhack\s*the\s*burgh\b/i,
    hostPatterns: [/hacktheburgh\.com$/i],
    faqPaths: ['/faq'],
    siteUrl: 'https://hacktheburgh.com/',
    evidence: 'Edinburgh student hackathon (~200 hackers); travel reimbursement offered some editions — verify FAQ',
  },
  {
    id: 'hackeurope',
    label: 'HackEurope',
    tier: 'B',
    region: 'eu',
    titlePattern: /\bhack\s*europe\b/i,
    hostPatterns: [/hackeurope\.com$/i],
    faqPaths: ['/faq'],
    siteUrl: 'https://www.hackeurope.com/',
    evidence: 'Pan-European multi-city student hackathon (Dublin/Paris/Stockholm); travel policy per edition — verify FAQ',
  },
  {
    id: 'ethrome',
    label: 'ETHRome',
    tier: 'B',
    region: 'eu',
    titlePattern: /\beth\s*rome\b/i,
    hostPatterns: [/ethrome\.org$/i],
    faqPaths: ['/faq'],
    siteUrl: 'https://www.ethrome.org/',
    evidence: 'Independent Web3 hackathon (Rome); builder travel/accommodation support varies by edition — verify',
  },
  {
    id: 'ethwarsaw',
    label: 'ETHWarsaw',
    tier: 'B',
    region: 'eu',
    titlePattern: /\beth\s*warsaw\b/i,
    hostPatterns: [/ethwarsaw\.(dev|com|org)$/i],
    faqPaths: ['/faq'],
    siteUrl: 'https://www.ethwarsaw.dev/',
    evidence: 'Poland Web3 hackathon; travel-partner discounts and selective builder grants — verify',
  },
  {
    id: 'ethprague',
    label: 'ETHPrague',
    tier: 'B',
    region: 'eu',
    titlePattern: /\beth\s*prague\b/i,
    hostPatterns: [/ethprague\.com$/i],
    faqPaths: ['/faq'],
    siteUrl: 'https://ethprague.com/',
    evidence: 'Independent Web3 hackathon (Prague); travel support varies by edition — verify',
  },
  {
    id: 'ethberlin',
    label: 'ETHBerlin',
    tier: 'B',
    region: 'eu',
    titlePattern: /\beth\s*berlin\b/i,
    hostPatterns: [/ethberlin\.(org|com|ooo)$/i],
    faqPaths: ['/faq'],
    siteUrl: 'https://ethberlin.org/',
    evidence: 'Independent Web3 hackathon (Berlin); travel support varies by edition — verify',
  },
  {
    id: 'imaginecup',
    label: 'Microsoft Imagine Cup',
    tier: 'B',
    region: 'global',
    titlePattern: /\bimagine\s*cup\b/i,
    hostPatterns: [/imaginecup\.microsoft\.com$/i],
    faqPaths: ['/faq'],
    siteUrl: 'https://imaginecup.microsoft.com/',
    evidence: 'Microsoft global student competition; covers travel to the World Championship for finalists',
  },
  {
    id: 'google-solution-challenge',
    label: 'Google Solution Challenge',
    tier: 'B',
    region: 'global',
    titlePattern: /\bsolution\s*challenge\b/i,
    hostPatterns: [/developers\.google\.com$/i],
    faqPaths: [],
    siteUrl: 'https://developers.google.com/community/gdsc-solution-challenge',
    evidence: 'Google student developer challenge; flies the top finalist teams to an in-person Demo Day',
  },
  {
    id: 'ethtokyo',
    label: 'ETHTokyo',
    tier: 'B',
    region: 'asia',
    titlePattern: /\beth\s*tokyo\b/i,
    hostPatterns: [/ethtokyo\.org$/i],
    faqPaths: ['/faq'],
    siteUrl: 'https://www.ethtokyo.org/',
    evidence: 'Independent Tokyo Ethereum hackathon (separate from ETHGlobal Tokyo); no travel program stated on site — FAQ-verified per edition',
  },
  {
    id: 'ethtaipei',
    label: 'ETHTaipei',
    tier: 'B',
    region: 'asia',
    titlePattern: /\beth\s*taipei\b/i,
    hostPatterns: [/ethtaipei\.org$/i],
    faqPaths: ['/faq'],
    siteUrl: 'https://ethtaipei.org/',
    evidence: 'Independent Taipei Ethereum hackathon (ETHGlobal-affiliated); travel support unconfirmed — FAQ-verified per edition',
  },
  {
    id: 'ethseoul',
    label: 'ETHSeoul',
    tier: 'B',
    region: 'asia',
    titlePattern: /\beth\s*seoul\b/i,
    hostPatterns: [/ethseoul\.(org|xyz)$/i],
    faqPaths: ['/faq'],
    siteUrl: 'https://ethseoul.org/',
    evidence: 'Seoul Ethereum hackathon (Korea Blockchain Week); travel support unconfirmed — FAQ-verified per edition',
  },
  {
    id: 'ethshanghai',
    label: 'ETHShanghai',
    tier: 'B',
    region: 'asia',
    titlePattern: /\beth\s*shanghai\b/i,
    hostPatterns: [/ethshanghai\.(org|xyz)$/i],
    faqPaths: ['/faq'],
    siteUrl: 'https://www.ethshanghai.org/',
    evidence: 'Shanghai Web3 hackathon; "Youth Hacker Voyage" subsidy (~200 USDT) is gated to young ASIAN developers — likely not applicable to EU builders',
  },
  {
    id: 'hedera-africa',
    label: 'Hedera Africa Hackathon',
    tier: 'B',
    region: 'africa',
    titlePattern: /\bhedera\s*africa\s*hackathon\b/i,
    hostPatterns: [/hederahackafrica\.com$/i],
    faqPaths: ['/faq'],
    siteUrl: 'https://hederahackafrica.com/',
    evidence: 'Largest-ever Web3 hackathon (13k devs, $1M prizes) but travel funding targets African participants — international-inbound travel unconfirmed',
  },
]
