// The brand mark: a coral glass jar (on a dark tile) filled with small flat
// circles in the portfolio accent colours — matches the PWA icon generated by
// scripts/gen-icons.mjs. "Cookie Jar" is the name; the logo is the jar.
const COLORS = ['#e5484d', '#ffb224', '#12a594', '#8e4ec6', '#0090ff', '#d6409f', '#30a46c']

// Uniform balls filling the round jar bottom (~a third full), viewed slightly
// from above: surface is an ellipse, sorted back-to-front for occlusion, each
// ball sphere-shaded. [cx, cy, colorIdx] — kept in sync with gen-icons.mjs.
const BALL_R = 15
const PILE: [number, number, number][] = [
  [274.2,325.7,5], [217,332.8,2], [287.4,333,5], [238.3,335.1,4], [327.7,339.6,3],
  [267.9,341.1,1], [296.9,344.2,1], [187.2,345.3,5], [220.3,346.8,6], [318.2,349.5,2],
  [197.3,350.6,2], [265.2,353.5,4], [235.8,355.8,1], [265.1,363.5,2], [299.9,365.1,6],
  [239.2,368.7,5], [212.7,371.4,0], [296.8,374.8,3], [262.7,375.1,6],
]

export default function CookieJarLogo({ size = 40 }: { size?: number }) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 512 512"
      className="shrink-0"
      style={{ boxShadow: '0 0 0 1px rgba(255,255,255,0.06) inset' }}
    >
      <defs>
        <radialGradient id="cjl-bg" cx="50%" cy="38%" r="75%">
          <stop offset="0" stopColor="#242427" />
          <stop offset="1" stopColor="#161618" />
        </radialGradient>
        <radialGradient id="cjl-glow" cx="50%" cy="50%" r="50%">
          <stop offset="0" stopColor="rgba(229,72,77,0.30)" />
          <stop offset="1" stopColor="rgba(229,72,77,0)" />
        </radialGradient>
        <radialGradient id="cjl-sphere" cx="36%" cy="32%" r="68%">
          <stop offset="0" stopColor="rgba(255,255,255,0.55)" />
          <stop offset="0.34" stopColor="rgba(255,255,255,0)" />
          <stop offset="1" stopColor="rgba(0,0,0,0.30)" />
        </radialGradient>
        <clipPath id="cjl-clip">
          <rect x="162" y="182" width="188" height="220" rx="36" />
        </clipPath>
      </defs>

      <rect x="0" y="0" width="512" height="512" rx="112" fill="url(#cjl-bg)" />
      <circle cx="256" cy="300" r="190" fill="url(#cjl-glow)" />

      {/* lid */}
      <rect x="170" y="120" width="172" height="40" rx="14" fill="#e5484d" />
      <rect x="160" y="152" width="192" height="22" rx="9" fill="#aa2429" />

      {/* glass body */}
      <rect
        x="156"
        y="176"
        width="200"
        height="232"
        rx="40"
        fill="rgba(229,72,77,0.08)"
        stroke="#e5484d"
        strokeWidth="11"
      />

      {/* flat circles inside */}
      <g clipPath="url(#cjl-clip)">
        {PILE.map(([cx, cy, c], i) => (
          <g key={i}>
            <circle cx={cx} cy={cy} r={BALL_R} fill={COLORS[c]} />
            <circle cx={cx} cy={cy} r={BALL_R} fill="url(#cjl-sphere)" />
          </g>
        ))}
      </g>

      {/* glass highlight */}
      <rect x="180" y="200" width="20" height="150" rx="10" fill="rgba(255,255,255,0.10)" />
    </svg>
  )
}
