// The brand mark: a coral glass jar (on a dark tile) filled with small flat
// circles in the portfolio accent colours — matches the PWA icon generated by
// scripts/gen-icons.mjs. "Cookie Jar" is the name; the logo is the jar.
const COLORS = ['#e5484d', '#ffb224', '#12a594', '#8e4ec6', '#0090ff', '#d6409f', '#30a46c']

// [cx, cy, r, colorIdx] — a naturally-settled pile (kept in sync with gen-icons.mjs)
const PILE: [number, number, number, number][] = [
  [192,386,11,6], [301,382,15,3], [268,384,13,4], [229,379,18,0], [326,373,12,3],
  [202,365,12,1], [281,360,14,5], [250,359,11,6], [315,353,11,4], [223,344,17,5],
  [191,335,16,6], [264,334,17,0], [299,331,16,1], [236,315,15,4], [327,323,13,5],
  [208,313,12,1], [278,302,18,4], [310,306,11,2], [187,299,13,3], [222,290,14,0],
  [324,284,15,1], [250,290,12,0], [198,273,15,3], [291,275,12,5], [265,272,12,4],
  [237,263,17,0], [312,259,13,5], [282,246,18,1], [207,242,17,0], [252,235,14,1],
  [321,230,17,4], [185,225,11,6], [229,225,11,3],
]

export default function CookieJarLogo({ size = 40 }: { size?: number }) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 512 512"
      className="shrink-0"
      style={{ boxShadow: '0 0 0 1px rgba(255,255,255,0.06) inset' }}
    >
      <defs>
        <radialGradient id="cjl-bg" cx="50%" cy="38%" r="75%">
          <stop offset="0" stopColor="#242427" />
          <stop offset="1" stopColor="#161618" />
        </radialGradient>
        <radialGradient id="cjl-glow" cx="50%" cy="50%" r="50%">
          <stop offset="0" stopColor="rgba(229,72,77,0.30)" />
          <stop offset="1" stopColor="rgba(229,72,77,0)" />
        </radialGradient>
        <clipPath id="cjl-clip">
          <rect x="162" y="182" width="188" height="220" rx="36" />
        </clipPath>
      </defs>

      <rect x="0" y="0" width="512" height="512" rx="112" fill="url(#cjl-bg)" />
      <circle cx="256" cy="300" r="190" fill="url(#cjl-glow)" />

      {/* lid */}
      <rect x="170" y="120" width="172" height="40" rx="14" fill="#e5484d" />
      <rect x="160" y="152" width="192" height="22" rx="9" fill="#aa2429" />

      {/* glass body */}
      <rect
        x="156"
        y="176"
        width="200"
        height="232"
        rx="40"
        fill="rgba(229,72,77,0.08)"
        stroke="#e5484d"
        strokeWidth="11"
      />

      {/* flat circles inside */}
      <g clipPath="url(#cjl-clip)">
        {PILE.map(([cx, cy, r, c], i) => (
          <circle key={i} cx={cx} cy={cy} r={r} fill={COLORS[c]} />
        ))}
      </g>

      {/* glass highlight */}
      <rect x="180" y="200" width="20" height="150" rx="10" fill="rgba(255,255,255,0.10)" />
    </svg>
  )
}
