// The brand mark: a coral glass jar (on a dark tile) filled with small flat
// circles in the portfolio accent colours — matches the PWA icon generated by
// scripts/gen-icons.mjs. "Cookie Jar" is the name; the logo is the jar.
const COLORS = ['#e5484d', '#ffb224', '#12a594', '#8e4ec6', '#0090ff', '#d6409f', '#30a46c']

// Uniform balls, jar ~a third full: [cx, cy, colorIdx] (kept in sync with gen-icons.mjs)
const BALL_R = 13
const PILE: [number, number, number][] = [
  [213,382,3], [311,382,5], [247,382,6], [277,382,2], [185,382,1], [294,362,6],
  [230,362,3], [327,361,6], [261,360,0], [198,360,4], [279,341,1], [310,341,2],
  [244,340,6], [216,340,1],
]

export default function CookieJarLogo({ size = 40 }: { size?: number }) {
  return (
    <svg
      width={size}
      height={size}
      viewBox="0 0 512 512"
      className="shrink-0"
      style={{ boxShadow: '0 0 0 1px rgba(255,255,255,0.06) inset' }}
    >
      <defs>
        <radialGradient id="cjl-bg" cx="50%" cy="38%" r="75%">
          <stop offset="0" stopColor="#242427" />
          <stop offset="1" stopColor="#161618" />
        </radialGradient>
        <radialGradient id="cjl-glow" cx="50%" cy="50%" r="50%">
          <stop offset="0" stopColor="rgba(229,72,77,0.30)" />
          <stop offset="1" stopColor="rgba(229,72,77,0)" />
        </radialGradient>
        <clipPath id="cjl-clip">
          <rect x="162" y="182" width="188" height="220" rx="36" />
        </clipPath>
      </defs>

      <rect x="0" y="0" width="512" height="512" rx="112" fill="url(#cjl-bg)" />
      <circle cx="256" cy="300" r="190" fill="url(#cjl-glow)" />

      {/* lid */}
      <rect x="170" y="120" width="172" height="40" rx="14" fill="#e5484d" />
      <rect x="160" y="152" width="192" height="22" rx="9" fill="#aa2429" />

      {/* glass body */}
      <rect
        x="156"
        y="176"
        width="200"
        height="232"
        rx="40"
        fill="rgba(229,72,77,0.08)"
        stroke="#e5484d"
        strokeWidth="11"
      />

      {/* flat circles inside */}
      <g clipPath="url(#cjl-clip)">
        {PILE.map(([cx, cy, c], i) => (
          <circle key={i} cx={cx} cy={cy} r={BALL_R} fill={COLORS[c]} />
        ))}
      </g>

      {/* glass highlight */}
      <rect x="180" y="200" width="20" height="150" rx="10" fill="rgba(255,255,255,0.10)" />
    </svg>
  )
}
